name: Deploy to Hostinger

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Install Dependencies
        run: composer install --no-progress --prefer-dist
      - name: Deploy to Hostinger
        run: rsync -avz --exclude '.git/' --exclude '.github/' --delete ./ u603298255@153.92.220.237:/domains/exklusives-katzenfutter.de/
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
